pipeline {
    agent any

   

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/swapnilrkGit/seleniumjava.git'
            }
        }

        stage('Build Project') {
            steps {
                bat 'mvn clean compile'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'mvn test'
            }
        }
    }

    post {
        always {
            // Publish TestNG results
            junit '/TESTCICD/test-output/emailable-report.html'
        }
    }
}
